version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - "5434:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - nestdev
networks:
  nestdev: {}  # Added mapping for the network